# AI Analysis Service Configuration
server:
  port: 8083  # Different port from main service (8082)

spring:
  application:
    name: coding-analysis-service

  # Database Configuration (same as your main service)
  datasource:
    url: jdbc:mysql://localhost:3306/leetcode_tracker?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
    username: root
    password: Makemegreat@1
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  # Jackson Configuration
  jackson:
    time-zone: Asia/Kolkata
    date-format: yyyy-MM-dd HH:mm:ss

# Perplexity AI Configuration
perplexity:
  api:
    key: ${PERPLEXITY_API_KEY}  # Set via environment variable
    base-url: https://api.perplexity.ai
    model: sonar-pro  # ✅ Use this instead of llama-3.1-sonar-large-128k-online
    timeout: 30000
    max-tokens: 1000
    temperature: 0.7

# Logging Configuration
logging:
  level:
    root: info
    ai.dsa.analysis: debug
    org.springframework.web: debug
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Management Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Application Configuration
app:
  analysis:
    default-period-days: 30
    max-code-samples: 10
    cache-ttl-minutes: 60


